---

- name: 'remove ifupdown so we can use netplan'
  apt:
    name: ifupdown
    state: absent
  when:
  - ct_distro == 'ubuntu'
  - ct_distro_major | int >= 18
  become: true
  tags:
  - ubuntu
  - ubuntu-network
  - ubuntu-pkg
  - netplan
  - x-pkg

- name: 'stat /etc/NetworkManager (check_mode=F,register)'
  stat:
    path: /etc/NetworkManager
  when:
  - ct_distro == 'ubuntu'
  - ct_distro_major | int >= 18
  - ct_network_engine == 'networkmanager'
  check_mode: false
  register: reg_nm
  tags:
  - ubuntu
  - ubuntu-network
  - networkmanager

- name: 'push NetworkManager.conf'
  copy:
    src: NetworkManager.conf
    dest: /etc/NetworkManager/NetworkManager.conf
    owner: root
    group: root
    mode: '0644'
  when:
  - ct_distro == 'ubuntu'
  - ct_distro_major | int >= 18
  - ct_network_engine == 'networkmanager'
  - reg_nm.stat.isdir is defined
  - reg_nm.stat.isdir
  become: true
  notify: handler_network_manager_config
  tags:
  - ubuntu
  - ubuntu-network
  - networkmanager

- name: 'manage Network Manager'
  service:
    name: network-manager
    enabled: "{{ (ct_network_engine == 'networkmanager') | ternary(true, false) }}"
    state: "{{ (ct_network_engine == 'networkmanager') | ternary('started', 'stopped') }}"
#   masked: "{{ (ct_network_engine == 'networkmanager') | ternary(false, true) }}"
  when:
  - ct_distro == 'ubuntu'
  - ct_distro_major | int >= 18
  - ct_provider is not defined
  become: true
  tags:
  - ubuntu
  - ubuntu-network
  - networkmanager

- name: 'manage systemd-networkd'
  service:
    name: systemd-networkd
    enabled: "{{ (ct_network_engine == 'networkd') | ternary(true, false) }}"
    state: "{{ (ct_network_engine == 'networkd') | ternary('started', 'stopped') }}"
  when:
  - ct_distro == 'ubuntu'
  - ct_distro_major | int >= 18
  - ct_container is not defined
  become: true
  tags:
  - ubuntu
  - ubuntu-network
  - networkd

- name: 'create /etc/netplan'
  file:
    path: /etc/netplan
    state: directory
    owner: root
    group: root
    mode: '0755'
  when:
  - ct_distro == 'ubuntu'
  - ct_distro_major | int >= 18
  - ct_provider is not defined
  - ct_network_engine == 'networkd'
  become: true
  tags:
  - ubuntu
  - ubuntu-network
  - netplan

- name: 'set up IP address via netplan (TODO)'  # TODO decide on process for vagrant
  template:
    src: netplan.j2
    dest: /etc/netplan/01-network-manager-all.yaml
    owner: root
    group: root
    mode: '0644'
  when:
  - ct_distro == 'ubuntu'
  - ct_distro_major | int >= 18
  - ct_provider is not defined
  - ct_network_engine == 'networkd'
  become: true
  notify: handler_netplan_ubuntu
  tags:
  - ubuntu
  - ubuntu-network
  - netplan

- name: 'render template for DHCP netplan example (TODO)'  # TODO decide on process for vagrant
  template:
    src: netplan-dhcp.yml.j2
    dest: /etc/netplan/00-nm-dhcp.example
    owner: root
    group: root
    mode: '0644'
  when:
  - ct_distro == 'ubuntu'
  - ct_distro_major | int >= 18
  - ct_provider is not defined
  - ct_network_engine == 'networkd'
  become: true
  tags:
  - ubuntu
  - ubuntu-network
  - netplan

- name: 'weekly cron job to clean up journal data'
  cron:
    name: 'journalctl-clean-up'
    state: present
    disabled: false
    user: root
    minute: '20'
    hour: '16'
    job: journalctl --vacuum-time=7d
    weekday: '1'  # Monday
  when:
  - ct_distro == 'ubuntu'
  - ct_distro_major | int >= 18
  become: true
  tags:
  - ubuntu
  - ubuntu-journalctl
  - x-cron
# alt arg = --vacuum-size=2G

...
